### ISSUE TITLE
why use my code for logger?

### ISSUE THREAD

**Issue by icyleaf** [mamantoha/crest#88]
i checked logger.cr and common_logger.cr both are 100% copy my halite code, why do that?

**Comment by mamantoha** [comment]
Hi @icyleaf.

Yeah, `Logger` is heavily inspired by (read: literally stolen) `halite` shard.  Because I liked the idea of your code.

If I am not mistaken, it does not violate MIT license. So, the answer is "why not?".

By the way, 95% of the code copied from Ruby's [rest-client](https://github.com/rest-client/rest-client) gem.

**Comment by icyleaf** [comment]
First you broken the MIT License: 
> The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.

Second i copied from rest-client and you write it to README, except halite.

That why i ask you.

**Comment by mamantoha** [comment]
Fixed in https://github.com/mamantoha/crest/commit/fdab83e0333c9d52b042662a6e467b24103057bb.

**Comment by icyleaf** [comment]
Thanks
